[package]
name = "phylax"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Phylax Monitoring Agent"
default-run = "phylax"

[dependencies]
# phylax
phylax-core.workspace = true
phylax-tracing.workspace = true
phylax-config.workspace = true
serde.workspace = true

phylax-evm.workspace = true
phylax-notifications.workspace = true


# reth
reth-cli-runner.workspace = true

#misc
clap.workspace = true
eyre.workspace = true
tracing.workspace = true

# async
tokio = { workspace = true, features = [
  "sync",
  "macros",
  "time",
  "rt-multi-thread",
] }
futures.workspace = true

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
tempfile = { workspace = true }

[features]
min-error-logs = ["tracing/release_max_level_error"]
min-warn-logs = ["tracing/release_max_level_warn"]
min-info-logs = ["tracing/release_max_level_info"]
min-debug-logs = ["tracing/release_max_level_debug"]
min-trace-logs = ["tracing/release_max_level_trace"]


[[bin]]
path = "src/main.rs"
name = "phylax"
