blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/phylax-systems/phylax/discussions/new?category=ideas
  - name: GitHub Discussions
    url: https://github.com/phylax-systems/phylax/discussions
    about: Please ask and answer questions here to keep the issue tracker clean.
  - name: Security
    url: mailto:odysseas@phylax.watch
    about: Please report security vulnerabilities here.
