[profile.default]
fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
sepolia = "https://ethereum-sepolia.publicnode.com"

[fmt]
# These are all the `forge fmt` defaults.
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = 'long'
multiline_func_header = 'attributes_first'
quote_style = 'double'
number_underscore = 'preserve'
single_line_statement_blocks = 'preserve'


[doc]
title = "Phylax Standard Library"
repository = "https://github.com/phylax-systems/phylax-std"
