name: Aggregate Phylax Docs

on:
  workflow_dispatch:
  push:
    branches: main
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: aggregate-phylax-docs
  cancel-in-progress: true

jobs:
  aggregate-docs:
    runs-on: ubuntu-latest
    name: Aggregate Phylax docs
    steps:
      - name: Checkout docs repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Checkout phylax docs
        uses: actions/checkout@v4
        with:
          repository: phylaxsystems/phylax
          path: temp/phylax
          sparse-checkout: |
            docs
          sparse-checkout-cone-mode: false
          token: ${{ secrets.GH_PAT }}

      - name: Organize docs
        run: |
          mkdir -p phylax
          cp -R temp/phylax/docs/* phylax/

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update docs
          file_pattern: '**/*'