name: Import Assertion Examples

on:
  # Option 1: Run when PRs are merged to main
  pull_request:
    types: [closed]
    branches: [main]

  # Option 2: Allow manual triggering
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Dry run (skip git push)"
        required: false
        default: true
        type: boolean

permissions:
  contents: write
  pull-requests: write

jobs:
  import-assertion-examples:
    # For PR events, only run when merged
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Create temporary directory and clone assertion-examples repository
        run: |
          # Create temporary directory
          TEMP_DIR=$(mktemp -d)
          echo "TEMP_DIR=$TEMP_DIR" >> $GITHUB_ENV

          # Clone into temporary directory using organization token
          git clone --depth 1 https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/phylaxsystems/assertion-examples.git "$TEMP_DIR/assertion-examples"

          echo "Directory structure:"
          find "$TEMP_DIR/assertion-examples" -type d | sort
          echo "Solidity files found:"
          find "$TEMP_DIR/assertion-examples" -name "*.sol" | sort

      - name: Create directories if they don't exist
        run: mkdir -p snippets

      - name: Copy and convert Solidity files to MDX
        run: |
          # Use the specific path to target only .sol files in assertions/src
          ASSERTIONS_PATH="$TEMP_DIR/assertion-examples/assertions/src"

          # Check if the directory exists
          if [ ! -d "$ASSERTIONS_PATH" ]; then
            echo "Error: Directory $ASSERTIONS_PATH not found"
            exit 1
          fi

          echo "Processing Solidity files from $ASSERTIONS_PATH:"
          find "$ASSERTIONS_PATH" -maxdepth 1 -name "*.sol" -type f | sort

          # Process all Solidity files in the specific directory (not subdirectories)
          find "$ASSERTIONS_PATH" -maxdepth 1 -name "*.sol" -type f | while read solidity_file; do
            base_filename=$(basename "$solidity_file" .sol)
            mdx_file="snippets/${base_filename}.mdx"
            
            # Create MDX file with Solidity content wrapped in code blocks
            echo -e "\`\`\`solidity\n$(cat $solidity_file)\n\`\`\`" > "$mdx_file"
            
            echo "Created $mdx_file from $solidity_file"
          done

          echo "Generated MDX files:"
          ls -la snippets/*.mdx || echo "No MDX files generated"

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: Import assertion examples from phylaxsystems/assertion-examples
          title: Update assertion examples
          body: |
            This PR automatically imports assertion examples from the [phylaxsystems/assertion-examples](https://github.com/phylaxsystems/assertion-examples) repository.

            The import was triggered by ${{ github.event_name == 'workflow_dispatch' && 'manual workflow run' || 'PR merge to main' }}.
          branch: update-assertion-examples
          delete-branch: true
          base: main
          reviewers: czepluch

      - name: Show pull request details
        if: steps.cpr.outputs.pull-request-operation != 'none'
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

      - name: Cleanup temporary directory
        if: always()
        run: |
          # Clean up temporary directory
          rm -rf "$TEMP_DIR"
          echo "Temporary directory removed"
