name: Aggregate Mintlify Docs

on:
  workflow_dispatch:
  push:
    branches: main
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: aggregate-mintlify-docs
  cancel-in-progress: true

jobs:
  aggregate-docs:
    runs-on: ubuntu-latest
    name: Aggregate mintlify docs
    steps:
      - name: Set git user
        run: |
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Run mintlify action
        uses: mintlify/multirepo-action@v0.15
        with:
          token: ${{ secrets.MINTLIFY_PUSH_TOKEN }}
          target-branch: main
          subdirectory: .
          repos: |
            - owner: phylaxsystems
              repo: phylaxsystems/phylax
            - owner: phylaxsystems
              repo: phylaxsystems/phylax-std
              ref: v1.0.0
