name: Spellcheck

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  codespell:
    name: Check Spelling with Codespell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Codespell
        uses: codespell-project/actions-codespell@v2 # Using latest v2.x release
        with:
          # Path to a file containing words to ignore, one word per line.
          ignore_words_file: .github/codespell_wordlist.txt

          # Optional: Specify the path for codespell to run on.
          # If you only want to check .mdx files, use the following pattern
          path: '"./**/*.mdx"'

          # Optional: Files or directories to skip.
          # Use a comma-separated list of glob patterns.
          skip: "snippets/*"
